server:
  port: 8037
camel:
  springboot:
    name: ServicesRest
    shutdown-timeout: 5
  component:
    servlet:
      mapping:
        context-path: /*
  rest:
    data-format-property:
      - prettyPrint: true
db:
  uri:  mongodb://localhost:12345
  database: database
  clientKeysCollection: client-api-keys
spring:
  main:
    allow-bean-definition-overriding: true
logging.level:
  org.apache.camel: INFO